name: "agnostic-sidecar-dev"

volumes:
  gamedata:
    driver: local
    
services:
  gameserver:
    image: itzg/minecraft-server
    environment:
      - EULA=TRUE
    volumes:
      - gamedata:/data
    ports:
      - "9999:9999"

  sidecar:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "service:gameserver"
    environment:
      - SIDECAR_INITIAL_DELAY=20s
      - SIDECAR_HEALTH_INTERVAL=15s
      - SIDECAR_PING_PORT=25565
      - SIDECAR_PING_PROTOCOL=tcp
      - SIDECAR_API_ADDR=:9999
      - SIDECAR_DATA_ROOT=/data
      - SIDECAR_RATE_LIMIT=8
    volumes:
      - gamedata:/data

  sdk-server:
    image: us-docker.pkg.dev/agones-images/release/agones-sdk:1.50.0
    command: --local
    network_mode: "service:gameserver"